languageCode = "en-us"
title = "SEAN'S FOOD BLOG!!"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
ignoreFiles= ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.posts]
    foldername = "post"
    pagesize = "6"

[params.settings]
    googleanalytics = "UA-113904582-3"
    disqus = "hugo-massively"
